function(cat IN_FILE OUT_FILE)
  file(READ ${IN_FILE} CONTENTS)
  file(APPEND ${OUT_FILE} "${CONTENTS}")
endfunction()

if(EXISTS "${DEST}")
  message(STATUS  "Up-to-date: ${DEST}")
else()
  find_program(OpenSSL_EXECUTABLE openssl)
  if(NOT OpenSSL_EXECUTABLE)
    message(STATUS "Bypassing : Unable to locate openssl to generate certificate")
  else()
    message(STATUS "Generating: ${DEST}")
    execute_process(COMMAND openssl ecparam -out ebftpd-ecdsa.key -name secp521r1 -genkey)
    execute_process(COMMAND openssl req -new -x509 -days 9000 -key ebftpd-ecdsa.key -out ebftpd-ecdsa.crt -subj "/CN=ebftpd")
    file(WRITE ebftpd-ecdsa.pem.in "")
    cat(ebftpd-ecdsa.key ebftpd-ecdsa.pem.in)
    cat(ebftpd-ecdsa.crt ebftpd-ecdsa.pem.in)
    configure_file(ebftpd-ecdsa.pem.in ${DEST} COPONLY)
    if(NOT EXISTS "${DEST}")
      message(WARNING "Error while generating certificate for TLS")
    endif()
  endif()
endif()
